[package]
name = "rust-jni-openssl"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustjniopenssl"
crate-type = ["dylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
openssl-sys = "0.9"
openssl = "0.10"
